// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzIlybdkclNSXcVmnjemjpl9usXyCnOHA',
    appId: '1:831676593114:web:5b1810efee6fc3bc1486e3',
    messagingSenderId: '831676593114',
    projectId: 'lavenda-app',
    authDomain: 'lavenda-app.firebaseapp.com',
    storageBucket: 'lavenda-app.appspot.com',
    measurementId: 'G-M0V4X8V2Y6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuGHG6ttXBAxi-EpNtXgfz4enKlIC0sL8',
    appId: '1:831676593114:android:3964b985b28423591486e3',
    messagingSenderId: '831676593114',
    projectId: 'lavenda-app',
    storageBucket: 'lavenda-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHkL445QCRCuavvNkNB2h0m4-z4gpeVbo',
    appId: '1:831676593114:ios:5de9308f9dc796e81486e3',
    messagingSenderId: '831676593114',
    projectId: 'lavenda-app',
    storageBucket: 'lavenda-app.appspot.com',
    iosBundleId: 'com.example.lavenda',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHkL445QCRCuavvNkNB2h0m4-z4gpeVbo',
    appId: '1:831676593114:ios:5de9308f9dc796e81486e3',
    messagingSenderId: '831676593114',
    projectId: 'lavenda-app',
    storageBucket: 'lavenda-app.appspot.com',
    iosBundleId: 'com.example.lavenda',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzIlybdkclNSXcVmnjemjpl9usXyCnOHA',
    appId: '1:831676593114:web:f319678fa5cdb8b11486e3',
    messagingSenderId: '831676593114',
    projectId: 'lavenda-app',
    authDomain: 'lavenda-app.firebaseapp.com',
    storageBucket: 'lavenda-app.appspot.com',
    measurementId: 'G-WG4ZNXQ6H2',
  );
}
